name: main
on: workflow_dispatch
jobs:
  build:
    uses: robert-koch-institut/OpenData-Workflows/.github/workflows/OpenData_Workflows.yml@main
    with:
      REF_NAME: $${{github.ref_name}}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}