name: main
on: workflow_dispatch
jobs:
  build:
    uses: robert-koch-institut/OpenData-Workflows/.github/workflows/OpenData_Workflows.yml@main
    with:
      OPENCODE_GROUPID: 4116
      OPENCODE_ACCESS_USER: knutperseke
    secrets:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      OPENCODE_TOKEN: ${{secrets.OPENCODE_TOKEN}}
      NFDI4HEALTH_CLIENT_ID: ${{secrets.NFDI4HEALTH_CLIENT_ID}}
      NFDI4HEALTH_CLIENT_SECRET: ${{secrets.NFDI4HEALTH_CLIENT_SECRET}}